### ISSUE TITLE
Suggestion: <tfc:metal/scrap/wrought_iron> to <tfc:metal/ingot/wrought_iron> in BlastFurnace

### ISSUE THREAD

**Issue by upidea** [AnodeCathode/TechNodeFirmaCraft#137]
In file Machines-ImmersiveEngineering.zs line:149
Change:
mods.immersiveengineering.BlastFurnace.addRecipe(<tfc:metal/ingot/pig_iron>, <tfc:metal/scrap/wrought_iron>, 598, <immersiveengineering:material:7>);
TO:
mods.immersiveengineering.BlastFurnace.addRecipe(<tfc:metal/ingot/wrought_iron>, <tfc:metal/scrap/wrought_iron>, 598, <immersiveengineering:material:7>);

In file Crafting-xnet.zs line:24
Change:
recipes.addShaped("xnet_facade", <xnet:facade> * 16, [[<minecraft:paper>, <minecraft:wool>, <minecraft:paper>], [<minecraft:wool>, <minecraft:glass>, <minecraft:wool>], [<minecraft:paper>, <minecraft:wool>, <minecraft:paper>]]);
TO:
recipes.addShaped("xnet_facade", <xnet:facade> * 16, [[<minecraft:paper>, <ore:fiberHemp>, <minecraft:paper>], [<ore:fiberHemp>, <minecraft:glass>, <ore:fiberHemp>], [<minecraft:paper>, <ore:fiberHemp>, <minecraft:paper>]]);

As, anything craft from <minecraft:wool> could be checked.:)

**Comment by Gaelmare** [comment]
The IE blast furnaces cooking iron scrap to pig iron is the mid-game path for steel production before/instead of the arc furnace. This is an intentional decision. 
As far as facades go, hemp fiber is much too cheap for this. Maybe burlap? I welcome your participation if you'd like to code that up and submit it as a Pull Request here!
