### ISSUE TITLE
Cannot extract molten Ferroboron from electric crucible

### ISSUE THREAD

**Issue by Broam** [AnodeCathode/TechNodeFirmaCraft#9]
![Screenshot from 2020-09-13 18-26-05](https://user-images.githubusercontent.com/1085080/93030113-9b9cfd80-f5ee-11ea-99b4-88a89cd71830.png)

Ingot mold never picks up metal

**Comment by AnodeCathode** [comment]
It's due to the chemical reconfiguration of the crystalline structure of the ferroboron matrix. It achieves a higher ion capture capability through the use of hand-waving and magic. There plausible. Although the inability to see the melting point of these alloys is an issue and something I'd like to tackle. In the meantime, I will likely bring boron's temp up past the induction crucibles max temp to prevent this issue. It likely is an issue with other metal/alloy combinations and I need a better long term solution

**Comment by AnodeCathode** [comment]
But the general recommendation would be not to use the induction crucible with the non-TFC alloys.
